### ISSUE TITLE
which git repos should be on server + how to test without getting in the way of each other on the server

### ISSUE THREAD

**Issue by legendOfZelda** [RDCEP/EDE#17]
@ricardobarroslourenco @njmattes on the server, how about we remove `ede_test` (i also want to remove it entirely from my github) and only work with `ede` (using branches) which also should be owned by group `ede` not by `njmattes`. and also, let us call it `EDE` just like the repo on github, not `ede` (i think i can safely just rename it right, since it's just the top-level directory and git still knows it's connected to `EDE.git`, e.g. when i do `git remote -v`?)

however, if we all use that same repo we are going to mess with each other's files (even though the file system is transactional, like a DB). so i suggest we have in `var/www/` subfolders for each one of us and then within those each one of us can have his clone of `EDE` and test with it.

or probably better: we only allow one person at a time to test, otherwise someone wants to recreate the `ede` db within postgres whereas someone else wants test the ingestion script, etc.

let me know what you think is best here

**Comment by njmattes** [comment]
Agree that we should remove the existing `ede_test`. I'd like to to leave the current `ede` as it is (although owned by `ede` group), since it's being served now by uWSGI and NGINX. 

I think we could have as many clones of the repo as we want, and their containing folders can be called anything we want (eg, `ede_severin`, with an `ede` module inside, thus keeping all imports intact). Inside the `ede` module is a `cedentials.py` file that contains db connection info. This is not in the repo now—you have to create one yourself for the time being. Eventually we should have an example file in the repo, but actual credentials should never be committed. If you edit this file to point to a different db (perhaps a db named `ede_severin`), then you should be able to test a fresh install without disturbing the live instance (since I'll be connecting the GUI to that eventually).

We'll also want to refactor some of the ingestion code to read the db settings from this `credentials.py` file. 

So...

```
cd /var/www
git clone https://github.com/RDCEP/EDE.git
mv EDE ede_severin
cd ede_severin # and install venv and dependencies
createdb ede_severin # and add postgis extension
cp /var/www/ede/ede/credentials ede/ # and edit credentials
# etc...
```

**Comment by njmattes** [comment]
Added a `credentials.py.example` file to the repo, and refactored the ingestion code to get db settings from the `credentials`.

**Comment by legendOfZelda** [comment]
great, thanx @njmattes
